title: deviceEventConfig
type: object
description: 'Represents the device events (warning, error) to be send asyncronously to the cloud'
properties:
  type:
    type: string
    enum:
      - warning
      - error
    description: The type of device event
  event:
    type: string
    enum:
      - os-update
      - ntp-offset
    description: The event to report
  threshold:
    description: The threshold at which the event is reported
    type: object
    properties:
      operator:
        type: string
        enum:
          - less-than
          - greater-than
          - equals
        description: The comparison operator to apply
      value:
        type: integer
        description: The threshold value
      unit:
        type: string
        enum:
          - seconds
          - milliseconds
          - degrees-celcius
          - degrees-farenheit
          - mb
          - kb
          - percent
        description: The threshold unit
    required:
      - operator
      - value
required:
  - type
  - event
