title: networkConfig
type: object
description: Represents reader communication configuration parameters.
properties:
  macAddress:
    type: string
    description: MAC address of the reader (read only)
    example: '84:24:8D:F0:F4:B5'
  dhcp:
    type: boolean
    description: A value indicating DHCP configuration
    example: 'true'
  dnsAddress:
    type: string
    description: IP address of the DNS server
    example: 8.8.8.8
  subnetMask:
    type: string
    description: Subnet mask for the network adapter
    example: 255.255.255.0
  gatewayAddress:
    type: string
    description: IP address of the gateway
    example: 192.168.1.1
  ipAddress:
    type: string
    description: IP address of the reader (read only if dhcp = true)
    example: 192.168.1.10
  hostName:
    type: string
    description: Host name of the reader
    example: FX9600F0F4B5
required:
  - macAddress
  - dhcp
  - dnsAddress
  - subnetMask
  - gatewayAddress
  - ipAddress
  - hostName
