openapi: 3.0.2
info:
  version: 1.0.0
  title: CloudConnect Reader REST API
  contact:
    url: 'http://zebra.com/support'
  x-logo:
    url: ./Zebra_Logo_K.png
  description:
    $ref: ./components/schemas/README.md
paths:
  /cloud/version:
    parameters: []
    get:
      operationId: get_version
      summary: Retrieves reader component version information
      description: 'Retrieves reader component version information including Boot Loader, OS, Reader Application, and Radio Firmware versions'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/schemas/readerversion.v1.yaml
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      tags:
        - Information
  /cloud/network:
    parameters: []
    get:
      summary: Retrieves reader network configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/schemas/readernetwork.v1.yaml
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: get_network
      description: 'Retrieves reader network information including IP address, subnet mask, gateway and DNS'
      tags:
        - Reader Configuration
    put:
      summary: Updates reader network configuration
      operationId: set_network
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      description: Updates the reader network configuration settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/readerNetworkSet.yaml
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      tags:
        - Reader Configuration
  /cloud/status:
    parameters: []
    get:
      summary: Retrieves reader operational statistics
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: ./components/schemas/readerstats.v1.yaml
                  - $ref: ./components/schemas/readerupgradestatus.v1.yaml
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: get_status
      description: Retrieves reader operational statistics for read points
      tags:
        - Information
  /cloud/reboot:
    parameters: []
    put:
      summary: Restarts reader
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: reboot
      description: Restarts the reader with the device ID provided
      tags:
        - Reader Actions
  /cloud/gpo:
    put:
      summary: Updates GPO port state
      operationId: set_gpo
      description: Updates the GPO state on the specified port of the reader
      parameters: []
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      tags:
        - Reader Actions
    parameters: []
  /cloud/app-led:
    get:
      summary: Retrieves application LED state
      operationId: get_appled
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      description: Retrieves a value indicating the current state of the application LED
      tags:
        - Reader Actions
    put:
      summary: Updates application LED state
      operationId: set_appled
      description: Updates the application LED state on the reader to the state specified
      parameters: []
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      tags:
        - Reader Actions
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/appled.v1.yaml
    parameters: []
  /cloud/region:
    parameters: []
    get:
      summary: Retrieves reader region information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/schemas/regionconfig.v1.yaml
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: get_region
      description: Retrieves reader region (country) information
      tags:
        - Reader Configuration
  /cloud/start:
    parameters: []
    put:
      summary: Starts reading tags
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: start
      description: Starts the reader reading tags
      tags:
        - RFID Actions
  /cloud/stop:
    parameters: []
    put:
      summary: Stops reading tags
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: stop
      description: Stops the reader reading tags
      tags:
        - RFID Actions
  /cloud/mode:
    get:
      summary: Retrieves operating mode
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/schemas/operatingMode.v1.yaml
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: get_mode
      description: Retrieves current operating mode
      tags:
        - RFID Configuration
    put:
      summary: Updates operating mode
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: set_mode
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/operatingMode.v1.yaml
        description: The new operation mode
      description: Changes the reader's operating mode
      tags:
        - RFID Configuration
    parameters: []
  /cloud/os:
    parameters: []
    put:
      summary: Updates software on device
      operationId: set_os
      description: Update the OS software on the device
      tags:
        - Reader Actions
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/os_update.v1.yaml
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
  /cloud/config:
    parameters: []
    get:
      summary: Retrieves reader configuration
      operationId: get_config
      description: Retrieves reader configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  xml:
                    type: string
                    description: The current reader configuration XML string
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      tags:
        - Reader Configuration
    put:
      summary: Updates reader configuration
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: set_config
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                xml:
                  type: string
                  description: The current reader configuration XML string
        description: The new reader configuration XML file
      description: Updates the reader configuration
      tags:
        - Reader Configuration
  /cloud/logs:
    get:
      summary: Log Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/schemas/logLevel.v1.json
          headers: {}
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: get_logs
      description: Retrieves reader log configuration
      tags:
        - Reader Configuration
    put:
      summary: Configures the logs
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: set_logs
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/logLevel.v1.json
        description: The log level to configure
      description: Changes logging level
      tags:
        - Reader Configuration
    parameters: []
  '/cloud/logs/{logType}':
    parameters:
      - schema:
          type: string
          enum:
            - syslog
            - radioPacketLog
        name: logType
        in: path
        required: true
        description: Type of Log to Retrieve
    get:
      summary: Retrieve Log
      responses:
        '200':
          description: OK
          content:
            application/gzip:
              schema:
                description: Reader Logs Retrieved
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      operationId: get_logs_syslog
      tags:
        - Reader Actions
      description: Retrieves a reader log
    delete:
      summary: Purge Log
      operationId: del_logs_syslog
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./components/schemas/error.v1.yaml
      description: Purges a particular log
      tags:
        - Reader Configuration
tags:
  - name: operating_mode
    x-displayName: Configuration for the Operating Modes
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/operatingModes" />
x-tagGroups:
  - name: Reader Management APIs
    tags:
      - Information
      - Reader Configuration
      - Reader Actions
  - name: RFID Control APIs
    tags:
      - RFID Configuration
      - RFID Actions
  - name: Schemas
    tags:
      - operating_mode
components:
  schemas:
    operatingModes:
      $ref: ./components/schemas/operatingMode.v1.yaml
